export const storeProducts=[
    {
    id:1,
    title: "Phones",
    img: "img/product-1.png",
    price:10,
    company:"GOOGLE",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,   
},

{
    id :2,
    title: "Laptops",
    img: "img/product-2.png",
    price:16,
    Company:"ADDAY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :3,
    title: "Desktop",
    img: "img/product-3.jpeg",
    price:25,
    Company:"BAYYNA",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :4,
    title: "Printer",
    img: "img/product-4.png",
    price:12,
    Company:"PAYNNU",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :5,
    title: "Powerbanks",
    img: "img/product-5.png",
    price:16,
    Company:"kloneY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :6,
    title: "Headset",
    img: "img/product-6.png",
    price:6,
    Company:"ADDAY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :7,
    title: "Laptops",
    img: "img/product-7.png",
    price:36,
    Company:"ADDAY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :8,
    title: "Laptops",
    img: "img/product-7.png",
    price:36,
    company:"ADDAY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
}]
export const detailsProduct ={
     id :1,
    title: "Laptops",
    img: "img/product-2.png",
    price:42,
    company:"ADDAY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0, 
   }
