export const storeProducts=[
    {
    id:1,
    title: "Drummer",
    img: "img/product-1.jpg",
    price:10,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,   
},

{
    id :2,
    title: "Guitarist",
    img: "img/product-2.jpg",
    price:16,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :3,
    title: "Palm Wine Tapper",
    img: "img/product-3.jpg",
    price:25,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :4,
    title: "Mood",
    img: "img/product-4.jpg",
    price:12,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :5,
    title: "Peace",
    img: "img/product-5.jpg",
    price:16,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :6,
    title: "Love",
    img: "img/product-6.jpg",
    price:6,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :7,
    title: "Family",
    img: "img/product-7.jpg",
    price:36,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :8,
    title: "Celebrate",
    img: "img/product-8.jpg",
    price:36,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :9,
    title: "Hustle",
    img: "img/product-9.jpg",
    price:36,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :10,
    title: "Night",
    img: "img/product-10.jpg",
    price:36,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :11,
    title: "Fruitfulness",
    img: "img/product-11.jpg",
    price:36,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},
{
    id :12,
    title: "Music",
    img: "img/product-12.jpg",
    price:36,
    Company:"ARTIFY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0,
},]
export const detailsProduct ={
     id :1,
    title: "Laptops",
    img: "img/product-2.jpg",
    price:42,
    company:"ADDAY",
    info:"Your first step in learning a skill is meant to be the hardest; as a woodworker,  your first cut usinga saw will be an herculean task, your first pedalling of a sewing machine as a fashion designer might be likened to climbing mount-Everest but whatsoever language you are learning as a programmer, yo are likely to start with HELLO WORLD, It is an announcement of your arrival into a career that expects you to solve problems on a daily. so i say Hello World!!! ",
    inCart:false,
    count:0,
    total:0, 
   }
